platform :ios, '12.0'

use_modular_headers!

target 'RideScout' do
  # Pods for RideScout
  pod 'EXImageLoader', :path => '../node_modules/expo-image-loader/ios'
  pod 'SDWebImageWebPCoder', :path => '../node_modules/react-native-webp'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'stripe-react-native', :path => '../node_modules/@stripe/stripe-react-native'

  # Expo dependencies
  pod 'ExpoModulesCore', :path => '../node_modules/expo-modules-core/ios'
  pod 'EXConstants', :path => '../node_modules/expo-constants/ios'
  pod 'Expo', :path => '../node_modules/expo/ios'
  pod 'ExpoAsset', :path => '../node_modules/expo-asset/ios'
  pod 'ExpoFileSystem', :path => '../node_modules/expo-file-system/ios'
  pod 'ExpoFont', :path => '../node_modules/expo-font/ios'
  pod 'ExpoImageManipulator', :path => '../node_modules/expo-image-manipulator/ios'
  pod 'ExpoImagePicker', :path => '../node_modules/expo-image-picker/ios'
  pod 'ExpoKeepAwake', :path => '../node_modules/expo-keep-awake/ios'
  pod 'ExpoMailComposer', :path => '../node_modules/expo-mail-composer/ios'

  # Add other pods here

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
